CREATE TABLE IF NOT EXISTS rent_vozila (
    id INT AUTO_INCREMENT PRIMARY KEY,
    igrac_id VARCHAR(50) NOT NULL,
    igrac_ime VARCHAR(100) NOT NULL,
    model VARCHAR(50) NOT NULL,
    cijena INT NOT NULL,
    vrijeme TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
